### ISSUE TITLE
[CLOSED] Evans Hunt - Jucier update for EV

### ISSUE THREAD

**Issue by ryanjohnston** [ryanjohnston/HomeDir#29]
<a href="https://github.com/ryanjohnston"><img src="https://avatars1.githubusercontent.com/u/137759?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [ryanjohnston](https://github.com/ryanjohnston)**
_Friday Feb 02, 2018 at 17:25 GMT_
_Originally opened as https://github.com/ryanjohnston/Journal/issues/128_

----

Jucier made a change to their json data due to a request from Twitter. The EV social dashboard screen is no longer showing any Twitter data, only Instagram. The page needs to be edited to have Twitter back.

# To Do
- [ ] Business Requirements

# Reference
- [ ] [SquareSpace Development Site]()
- [ ] [SquareSpace Development Server]()

# See Also
- [ ] #32 Business Requirements
- [ ] #69 JavaScript Development on MacOS
- [ ] #96 SquareSpace Resources & Workflow
- [ ] #95 Dockerize SquareSpace Development
- [ ] #33 Development Workflow
- [ ] #37 List of Development Software

**Comment by ryanjohnston** [comment]
<a href="https://github.com/ryanjohnston"><img src="https://avatars1.githubusercontent.com/u/137759?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ryanjohnston](https://github.com/ryanjohnston)**
_Saturday Feb 03, 2018 at 11:56 GMT_

----

- Updated EHdevelopment repo with documentation on how to work with EV codebase and SquareSpace. [https://github.com/ryanjohnston/EHDevelopment/commit/c9e3cb313618b327e23cac0043c389b157e787ad](https://github.com/ryanjohnston/EHDevelopment/commit/c9e3cb313618b327e23cac0043c389b157e787ad)
